site_name: Jiemeng
site_url: https://vescrity.github.io/Jiemeng_Doc
theme:
  language: zh
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy 
    - navigation.footer
    - navigation.instant      # 内部链接即时加载
    - navigation.tabs         # 页顶导航栏
    - navigation.tabs.sticky  # 粘性导航栏
    - navigation.top          # 回到顶部
    - toc.follow              # 边栏自动滚动


markdown_extensions: # markdown扩展插件
  - admonition # 启用注释语法扩展
  - pymdownx.arithmatex: # 数学公式支持
      generic: true
  - pymdownx.caret # 下划线与上标
  - pymdownx.details # 启用注释语法扩展
  - pymdownx.mark # 强调
  - pymdownx.superfences # 启用注释语法扩展
  - pymdownx.tilde # 删除线与下标
  - meta

nav:
  - "index.md"
  - start.md
  - 配置:
    - config/config.md
    - config/answer.md
  - 牌堆:
    - deck/index.md
  - 插件:
    - plugins/index.md
